In [1]:
import torch
import numpy as np
import math

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
data =[[1,2],[3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5748, 0.5315],
        [0.9855, 0.5774]])



In [5]:
shape = (2,3)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
torch.manual_seed(1789)
rand_tensor = torch.rand(shape)
empty_tensor = torch.empty(shape)
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"zeros Tensor: \n {zeros_tensor}\n")
print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Empty Tensor: \n {empty_tensor}\n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random Tensor: 
 tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]])

Empty Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [6]:
x = torch.empty(2,2,3)
print(x.shape, "\n")
print(x)

torch.Size([2, 2, 3]) 

tensor([[[7.9467e+11, 3.1473e-41, 0.0000e+00],
         [0.0000e+00, 1.8727e-14, 3.1469e-41]],

        [[1.0842e-19, 0.0000e+00, 4.6241e+30],
         [1.0552e+24, 5.5757e-02, 1.8728e+31]]])


In [7]:
a = torch.ones((2,3), dtype=torch.int8)
print(a)
print(a.dtype)
print("\n")
a = torch.ones((2,3), dtype=torch.int64)
print(a)
print(a.dtype)
print("\n")
a = torch.ones((2,3), dtype=torch.bool)
print(a)
print(a.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)
torch.int8


tensor([[1, 1, 1],
        [1, 1, 1]])
torch.int64


tensor([[True, True, True],
        [True, True, True]])
torch.bool


In [8]:
tensor = torch.rand(3,2)
print(f"device tensor is initially stored on: {tensor.device}")

device tensor is initially stored on: cpu


In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"device tensor is now stored on: {tensor.device}")
else:
    print("cuda is not available")


device tensor is now stored on: cuda:0


In [11]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]} \n")
print(f"First column: {tensor[:,0]} \n")
print(f"Last column: {tensor[:,-1]} \n")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
ones = torch.zeros(2, 2) + 1
twos = (torch.ones(2, 2) * 2)
threes = (torch.ones(2,2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [22]:
powers2 = twos ** torch.tensor([[1,2], [3,4]])
print(powers2, "\n")

fives = ones + fours
print(fives, "\n")

dozens = threes * fours
print(dozens, "\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[5., 5.],
        [5., 5.]]) 

tensor([[12., 12.],
        [12., 12.]]) 



In [28]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1,4) * 2)
print(rand)
print(doubled)

tensor([[0.6428, 0.3502, 0.8198, 0.1592],
        [0.0902, 0.7986, 0.4120, 0.8499]])
tensor([[1.2857, 0.7005, 1.6397, 0.3183],
        [0.1804, 1.5973, 0.8240, 1.6998]])


In [34]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b, "\n")

c = a * torch.rand(4, 1, 2)
print(c, "\n")

d = a * torch.rand(1, 3, 2)
print(d, "\n")

tensor([[[0.5300, 0.3159],
         [0.7081, 0.1727],
         [0.9051, 0.5988]],

        [[0.5300, 0.3159],
         [0.7081, 0.1727],
         [0.9051, 0.5988]],

        [[0.5300, 0.3159],
         [0.7081, 0.1727],
         [0.9051, 0.5988]],

        [[0.5300, 0.3159],
         [0.7081, 0.1727],
         [0.9051, 0.5988]]]) 

tensor([[[0.2455, 0.1117],
         [0.2455, 0.1117],
         [0.2455, 0.1117]],

        [[0.2259, 0.1532],
         [0.2259, 0.1532],
         [0.2259, 0.1532]],

        [[0.4302, 0.6361],
         [0.4302, 0.6361],
         [0.4302, 0.6361]],

        [[0.7443, 0.7234],
         [0.7443, 0.7234],
         [0.7443, 0.7234]]]) 

tensor([[[0.7417, 0.6321],
         [0.2893, 0.1629],
         [0.1285, 0.9058]],

        [[0.7417, 0.6321],
         [0.2893, 0.1629],
         [0.1285, 0.9058]],

        [[0.7417, 0.6321],
         [0.2893, 0.1629],
         [0.1285, 0.9058]],

        [[0.7417, 0.6321],
         [0.2893, 0.1629],
         [0.1285, 0.9058]]]) 

In [38]:
# Mathematical Functions

a = torch.rand(2,4)
print(torch.abs(a), "\n")
print(torch.ceil(a), "\n")
print(torch.floor(a), "\n") 
print(torch.clamp(a, -0.5, 0.5), "\n")

tensor([[0.8680, 0.0246, 0.3889, 0.4033],
        [0.4086, 0.0129, 0.4722, 0.5735]]) 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

tensor([[0.5000, 0.0246, 0.3889, 0.4033],
        [0.4086, 0.0129, 0.4722, 0.5000]]) 



In [41]:
#Trigonometric Functions -> not in degree but in radians
angles = torch.tensor([0, math.pi/4, math.pi/2, 3 * math.pi/4, math.pi])
sines = torch.sin(angles)
arcsines = torch.asin(sines)
print("Angles, Sines and Arc Sines:")
print(angles, "\n")
print(sines, "\n")
print(arcsines, "\n")


Angles, Sines and Arc Sines:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416]) 

tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08]) 

tensor([ 0.0000e+00,  7.8540e-01,  1.5708e+00,  7.8540e-01, -8.7423e-08]) 



In [42]:
#Bitwise Operations
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])

print(torch.bitwise_xor(b, c), "\n")

tensor([3, 2, 1]) 



In [43]:
# Comparison Operations
print("Broadcasted, element-wise comparison operations:")
d = torch.tensor([[1., 2.], [3., 4.]])
print(d, "\n")
e = torch.ones(1,2)
print(e, "\n")
print(torch.eq(d, e), "\n")

Broadcasted, element-wise comparison operations:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]]) 



In [45]:
# Reductions

d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d), "\n")
print(torch.max(d).item(), "\n")
print(torch.mean(d), "\n")
print(torch.std(d), "\n")
print(torch.prod(d), "\n")
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])), "\n")


tensor(4.) 

4.0 

tensor(2.5000) 

tensor(1.2910) 

tensor(24.) 

tensor([1, 2]) 



In [47]:
# Vector Operations and Linear Algebra Operations
v1 = torch.tensor([1.,0.,0.]) #x unit vector
v2 = torch.tensor([1.,0.,0.]) #y unit vector

print(torch.linalg.cross(v1,v2), "\n") #returns cross products

m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.],[0.,3.]])
print(m1, "\n")
m3 = torch.matmul(m1,m2)
print(m3, "\n")
print(torch.svd(m3), "\n")

tensor([0., 0., 0.]) 

tensor([[0.6007, 0.5485],
        [0.5868, 0.3942]]) 

tensor([[1.8022, 1.6454],
        [1.7603, 1.1827]]) 

torch.return_types.svd(
U=tensor([[-0.7553, -0.6554],
        [-0.6554,  0.7553]]),
S=tensor([3.2244, 0.2373]),
V=tensor([[-0.7800,  0.6258],
        [-0.6258, -0.7800]])) 



In [48]:
a = torch.tensor([0, math.pi/4, math.pi/2, 3 * math.pi/4, math.pi])
print('a:')
print(a)
print(torch.sin(a))
print(a)


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])


In [50]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)
print("Before: ")
print(a)
print(b)
print("\nAfter adding: ")
print(a.add_(b))
print("\nAfter multiplying: ")  
print(a.mul_(b))

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])

After adding: 
tensor([[2., 2.],
        [2., 2.]])

After multiplying: 
tensor([[2., 2.],
        [2., 2.]])


In [87]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    try:
        device = torch.device("mps")
        print("MPS available!")
    except:
        print('Sorry, CPU only.')


We have a GPU!


In [88]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    try:
        my_device = torch.device("mps")
    except:
        my_device = torch.device('cpu')

x = torch.rand(2, 2, device=my_device)
print(x)

tensor([[0.6425, 0.8167],
        [0.8363, 0.1061]], device='cuda:0')


# Questions

In [46]:
# 1.Obtain a tensor containing only zeros from the given tensor
pattern = torch.tensor([
    [1,1,1,1],
    [1,0,0,1],
    [1,0,0,1],
    [1,1,1,1]
])

zeros = torch.zeros_like(pattern)
print(zeros, "\n")


tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]) 



In [24]:
# 2.Create NumPy array of shape (1, 3, 3) using PyTorch
np_array = torch.ones(3,3).numpy()
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# 3.Create two random (2, 2, 2) tensors and find the min, max, mean, std of their product (matrix multiplication)

a = torch.rand(2,2,2)
b = torch.rand(2,2,2)
product = torch.matmul(a,b)
print(product)

print(f"\nMin: {product.min()}")
print(f"Max: {product.max()}")
print(f"Mean: {product.mean()}")
print(f"Standard Deviation: {product.std()}")
print("\n")



tensor([[[0.4983, 0.1046],
         [0.3991, 0.2752]],

        [[0.0825, 0.4450],
         [0.0422, 0.1573]]])

Min: 0.042207006365060806
Max: 0.49827149510383606
Mean: 0.25052955746650696
Standard Deviation: 0.17867928743362427




In [32]:
# 4.Convert a 16x16 tensor in 1x256 tensor

a = torch.ones(16,16)
print(a)
b = torch.reshape(a, (1,256))
print(b)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1

In [37]:
# 5.Given two tensor x and y, find the coefficient that best model the linear relationship Y = ax + b (Linear Regression)
# b = sigma (xi - x)(yi - y) / sigma (xi - x)^2
# a = y - bx

x = torch.rand(10)
y = 2 * x + 1 + torch.randn(10) * 0.1

x_mean = torch.mean(x)
y_mean = torch.mean(y)

b = torch.sum((x - x_mean) * (y - y_mean)) / torch.sum((x - x_mean) ** 2)
a = y_mean - b * x_mean

print(f"a: {a}\nb: {b}")



a: 1.1349598169326782
b: 1.742231845855713


In [51]:
# 6.Perform element-wise multiplication and addition on two 3x3 tensors

a = torch.rand(3,3)
b = torch.rand(3,3)

print(f"a: {a}\nb: {b}")
print(f"Element-wise multiplication: {a * b}")
print(f"Element-wise addition: {a + b}")

a: tensor([[0.5936, 0.4024, 0.0911],
        [0.0035, 0.2118, 0.5679],
        [0.5858, 0.9733, 0.3692]])
b: tensor([[0.1148, 0.3430, 0.5337],
        [0.8697, 0.6151, 0.2620],
        [0.7743, 0.8910, 0.1941]])
Element-wise multiplication: tensor([[0.0682, 0.1380, 0.0486],
        [0.0031, 0.1303, 0.1488],
        [0.4536, 0.8672, 0.0716]])
Element-wise addition: tensor([[0.7084, 0.7454, 0.6248],
        [0.8732, 0.8269, 0.8299],
        [1.3602, 1.8643, 0.5633]])


In [52]:
# 7.Stack two 2x3 tensors along a new dimension

a = torch.rand(2,3)
b = torch.rand(2,3)

print(f"a: {a}\nb: {b}")
print(f"Stacked tensors: {torch.stack((a,b))}")


a: tensor([[0.9210, 0.6140, 0.6969],
        [0.4786, 0.0187, 0.8875]])
b: tensor([[0.9846, 0.3264, 0.3193],
        [0.0828, 0.2082, 0.1284]])
Stacked tensors: tensor([[[0.9210, 0.6140, 0.6969],
         [0.4786, 0.0187, 0.8875]],

        [[0.9846, 0.3264, 0.3193],
         [0.0828, 0.2082, 0.1284]]])


In [53]:
# 8.Create a 1D tensor with values ranging from 0 to 9

a = torch.arange(10)
print(a)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [57]:
# 9.Perform operations on tensors of different shapes: 2x3 and 1x3 tensor using broadcasting

a = torch.rand(2,3)
b = torch.rand(1,3)

print(f"a: {a}\nb: {b}\n")
print(f"Element-wise multiplication: {a * b}")

a: tensor([[0.9086, 0.1219, 0.5926],
        [0.0131, 0.0058, 0.1323]])
b: tensor([[0.4359, 0.4114, 0.9087]])

Element-wise multiplication: tensor([[0.3961, 0.0502, 0.5385],
        [0.0057, 0.0024, 0.1202]])


In [54]:
# 10.Reshape a 1D tensor with 12 elements into a 3x4 matrix

a = torch.arange(12)
print(f"a: {a}")
b = torch.reshape(a, (3,4))
print(f"b: {b}")

a: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
b: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [55]:
# 11.Compute the sum of all elements in a 5x5 tensor.

a = torch.rand(5,5)
print(f"a: {a}")
print(f"Sum of all elements: {torch.sum(a)}")


a: tensor([[0.7802, 0.7778, 0.3140, 0.0638, 0.1032],
        [0.7553, 0.3410, 0.5284, 0.0245, 0.1815],
        [0.4078, 0.0718, 0.7933, 0.4388, 0.3995],
        [0.4898, 0.6255, 0.5537, 0.4507, 0.7321],
        [0.5065, 0.4272, 0.3635, 0.7104, 0.5528]])
Sum of all elements: 11.393038749694824


In [58]:
# 12.Transpose a 3x4 tensor into a 4x3 tensor

a = torch.rand(3,4)
print(f"a: {a}")
b = torch.transpose(a, 0, 1)
print(f"b: {b}")

a: tensor([[0.1500, 0.3061, 0.5663, 0.9953],
        [0.9274, 0.5454, 0.0943, 0.3650],
        [0.4334, 0.2278, 0.7780, 0.4037]])
b: tensor([[0.1500, 0.9274, 0.4334],
        [0.3061, 0.5454, 0.2278],
        [0.5663, 0.0943, 0.7780],
        [0.9953, 0.3650, 0.4037]])


In [59]:
# 13.Normalize a 1D tensor so that its values are in the range [0, 1].

a = torch.rand(10)
print(f"a: {a}")
a_min = torch.min(a)
a_max = torch.max(a)
a = (a - a_min) / (a_max - a_min)
print(f"Normalized a: {a}")


a: tensor([0.8859, 0.9238, 0.4491, 0.1927, 0.6963, 0.2912, 0.5913, 0.2936, 0.7483,
        0.8779])
Normalized a: tensor([0.9482, 1.0000, 0.3506, 0.0000, 0.6888, 0.1346, 0.5452, 0.1380, 0.7600,
        0.9372])


In [60]:
# 14.Concatenate two tensors of shape (2, 3) along dimension 1.

a = torch.rand(2,3)
b = torch.rand(2,3)

print(f"a: {a}\nb: {b}")
print(f"Concatenated tensors: {torch.cat((a,b), 1)}")

a: tensor([[0.2784, 0.1635, 0.6878],
        [0.7586, 0.5219, 0.0224]])
b: tensor([[0.2237, 0.7434, 0.5412],
        [0.3971, 0.2491, 0.0272]])
Concatenated tensors: tensor([[0.2784, 0.1635, 0.6878, 0.2237, 0.7434, 0.5412],
        [0.7586, 0.5219, 0.0224, 0.3971, 0.2491, 0.0272]])


In [61]:
# 15.Apply a ReLU activation function to a 2D tensor.

a = torch.randn(2,2)
print(f"a: {a}")
a = torch.relu(a)
print(f"ReLU(a): {a}")

a: tensor([[-0.1452,  0.7421],
        [ 3.8234,  1.4392]])
ReLU(a): tensor([[0.0000, 0.7421],
        [3.8234, 1.4392]])


In [62]:
# 16.Create a tensor of shape (5, 5) with random integers between 0 and 10, and compute the median of each row.

a = torch.randint(0, 10, (5,5))
print(f"a: {a}")
print(f"Median of each row: {torch.median(a, 1).values}")


a: tensor([[1, 3, 2, 5, 2],
        [2, 2, 8, 8, 1],
        [8, 6, 6, 0, 5],
        [0, 3, 5, 0, 7],
        [2, 5, 9, 6, 1]])
Median of each row: tensor([2, 2, 6, 3, 5])


In [65]:
# 17.Perform element-wise division of two tensors with shapes (3, 2) and (2, 3) using broadcasting.

a = torch.rand(3,2)
b = torch.rand(2,3)

print(f"a: {a}\nb: {b}\n")
print(f"Element-wise division: {a.unsqueeze(2) / b.unsqueeze(0)}")


a: tensor([[0.4923, 0.4461],
        [0.5020, 0.4484],
        [0.3091, 0.2227]])
b: tensor([[0.2154, 0.0467, 0.0423],
        [0.5964, 0.7368, 0.2158]])

Element-wise division: tensor([[[ 2.2852, 10.5361, 11.6475],
         [ 0.7480,  0.6055,  2.0671]],

        [[ 2.3301, 10.7434, 11.8766],
         [ 0.7518,  0.6085,  2.0774]],

        [[ 1.4349,  6.6158,  7.3137],
         [ 0.3734,  0.3023,  1.0319]]])


In [66]:
# 18.Initialize a tensor of shape (2, 4) with values from a uniform distribution and perform a matrix multiplication with a (4, 3) tensor.

a = torch.rand(2,4)
b = torch.rand(4,3)

print(f"a: {a}\nb: {b}\n")
print(f"Matrix multiplication: {torch.matmul(a,b)}")


a: tensor([[0.4919, 0.9087, 0.4816, 0.5931],
        [0.9008, 0.9913, 0.8031, 0.0939]])
b: tensor([[0.9091, 0.9111, 0.0913],
        [0.4713, 0.9345, 0.3078],
        [0.3529, 0.2206, 0.8371],
        [0.8664, 0.6600, 0.4606]])

Matrix multiplication: tensor([[1.5593, 1.7950, 1.0009],
        [1.6509, 1.9863, 1.1029]])


In [86]:
# 19.Create a tensor of shape (2, 2, 3) with values ranging from 0 to 8, and perform a 2D convolution with a (2, 2) kernel.
# the 12 values need to lie in between 0 to 9 for the tensor (2, 2, 3)

tensor = torch.tensor([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [0, 1, 2]]], dtype=torch.float32)
kernel = torch.tensor([[1, 0], [0, 1]], dtype=torch.float32)

print(f"Tensor: {tensor}\n")
print(f"Kernel: {kernel}\n")

#using for 2 for loops
output = torch.zeros(1, 1, 2, 2)
for i in range(2):
    for j in range(2):
        output[0, 0, i, j] = torch.sum(tensor[i:i+2, j:j+2] * kernel)
    print(f"Output: {output}")


Tensor: tensor([[[0., 1., 2.],
         [3., 4., 5.]],

        [[6., 7., 8.],
         [0., 1., 2.]]])

Kernel: tensor([[1., 0.],
        [0., 1.]])



RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [75]:
# 20.Convert a tensor with shape (4, 2) into a 2D NumPy array of shape (2, 4).

a = torch.rand(4,2)
print(f"a: {a}")
b = a.numpy().reshape(2,4)
print(f"Reshaped array of shape(2,4): {b}")



a: tensor([[0.7993, 0.1799],
        [0.4700, 0.5255],
        [0.6726, 0.6271],
        [0.6292, 0.5213]])
Reshaped array of shape(2,4): [[0.7992935  0.1799388  0.46997768 0.52553326]
 [0.6725904  0.6270688  0.62917423 0.5212817 ]]
